### ISSUE TITLE
Comment on a commit when failure/success

### ISSUE THREAD

**Issue by keskad** [kube-cicd/pipelines-feedback-core#3]
Enchancement proposal - on each commit there could be added a comment with the Pipeline status - optionally.

```yaml
---
apiVersion: pipelinesfeedback.keskad.pl/v1alpha1
kind: PFConfig
metadata:
    name: keskad-sample-1
spec:
    jobDiscovery: {}
data:
    jxscm.comment-commit: "true"                        # defaults to "false"
    jxscm.comment-commit-on-success: "true"   # defaults to "false"

```
