### ISSUE TITLE
Specify a priority of PFConfig merging

### ISSUE THREAD

**Issue by keskad** [kube-cicd/pipelines-feedback-core#47]
In order to make sure PFConfig changes are merged as expected there could be an optional `priorityWeight` field that describes how important is particular `PFConfig` .

`PFConfigs` could be sorted by `priorityWeight` ascending, so the `PFConfig` with highest value wins in the merging order.

```yaml
---
apiVersion: pipelinesfeedback.keskad.pl/v1alpha1
kind: PFConfig
metadata:
    name: keskad-sample-1
spec:
    jobDiscovery: {}
    priorityWeight: 100 # defaults to 0
data:
    # ...
```
